# Generated by Django 5.2.8 on 2025-11-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
