deps:
	npm i
	uv sync
dev:
	DEBUG=true uv run manage.py runserver

# Runs production server.
prod: static
	uv run gunicorn django_project.wsgi:application --workers `nproc` --worker-class gevent
format:
	uv run ruff check --select I --fix; uv run ruff format
	npx prettier --write **/*.html

static: tailwind-no-watch
	uv run manage.py collectstatic --noinput

static-no-cache:
	rm static_root -r
	just static

cache:
	mkdir -p .cache

	if [ ! -f "./.cache/input.css" ]; then \
		echo '@import "tailwindcss";' > ./.cache/input.css; \
		echo '@source not "./tailwindcss";' >> ./.cache/input.css; \
		echo '@source not "./daisyui{,*}.mjs";' >> ./.cache/input.css; \
		echo '@plugin "./daisyui.mjs";' >> ./.cache/input.css; \
	fi

	if [ ! -f "./.cache/tailwindcss" ]; then \
		curl -Lo .cache/tailwindcss https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64; \
		chmod +x ./.cache/tailwindcss; \
	fi
	[ -f "./.cache/daisyui.mjs" ] || curl -Lo .cache/daisyui.mjs https://github.com/saadeghi/daisyui/releases/latest/download/daisyui.mjs
	[ -f "./.cache/daisyui-theme.mjs" ] || curl -Lo .cache/daisyui-theme.mjs https://github.com/saadeghi/daisyui/releases/latest/download/daisyui-theme.mjs

# You can ignore the `sh: 1: watchman: not found` error (it will fallback to another watcher). This starts tailwind to watch HTML changes across the whole project and recompile the output.css.
tailwind: cache
	./.cache/tailwindcss -i ./.cache/input.css -o static/core/output.css --watch

tailwind-no-watch: cache
	./.cache/tailwindcss -i ./.cache/input.css -o static/core/output.css
