dev:
	DEBUG=true uv run manage.py runserver
# Runs production server. Remember to run `just static` before running this script
prod:
	uv run gunicorn django_project.wsgi:application --workers `nproc` --worker-class gevent
static:
	uv run manage.py collectstatic --noinput
opt:
	mkdir -p .opt
	if [ ! -f "./.opt/tailwindcss" ]; then \
		curl -sLo .opt/tailwindcss https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64; \
		chmod +x ./.opt/tailwindcss; \
	fi
	[ -f "./.opt/daisyui.mjs" ] || curl -sLo .opt/daisyui.mjs https://github.com/saadeghi/daisyui/releases/latest/download/daisyui.mjs
	[ -f "./.opt/daisyui-theme.mjs" ] || curl -sLo .opt/daisyui-theme.mjs https://github.com/saadeghi/daisyui/releases/latest/download/daisyui-theme.mjs
# run `just opt` to download necessary optional files before running this command. You can ignore the `sh: 1: watchman: not found` error (it will fallback to another watcher). This starts tailwind to watch HTML changes across the whole project and recompile the output.css.
tw:
	./.opt/tailwindcss -i static/core/input.css -o static/core/output.css --watch
